### ISSUE TITLE
Standalone Vue.js component

### ISSUE THREAD

**Issue by kolaente** [muhammederdem/credit-card-form#4] opened 2019-10-24 20:17 UTC
Hey there, I really like it!

What do you think of distributing it as a standalone vue component via npm?

**Comment by muhammederdem** [comment] 2019-10-25 10:20
this issue is a dublicate of #3

**Comment by muhammederdem** [comment] 2019-10-25 10:21
Hi @kolaente  this issue is duplicate of #3

**Closed by muhammederdem** 2019-10-25 10:21 UTC
